# word.yml
--- 
asw.sentence: 
  wordservice: 
    words: test,test,test,test

--- 
spring: 
  profiles: subject

server: 
  port: 8081

asw.sentence: 
  wordservice: 
    words: Spring Cloud Config,Spring Cloud Config
  
--- 
spring: 
  profiles: verb

server: 
  port: 8082

asw.sentence: 
  wordservice: 
    words: works,works
  
--- 
spring: 
  profiles: object

server: 
  port: 8083

asw.sentence: 
  wordservice: 
    words: from remote files,from remote files