# word.yml
--- 
asw: 
  sentenceservice: 
    word: 
      words: test,test,test,test

--- 
spring: 
  profiles: subject

server: 
  port: 8081

asw: 
  sentenceservice: 
    word: 
      words: Spring Cloud Config,Spring Cloud Config
  
--- 
spring: 
  profiles: verb

server: 
  port: 8082

asw: 
  sentenceservice: 
    word: 
      words: works,works
  
--- 
spring: 
  profiles: object

server: 
  port: 8083

asw: 
  sentenceservice: 
    word: 
      words: from remote files,from remote files