# application.yml
--- 
spring: 
  application: 
    name: default

server: 
  port: ${PORT:${SERVER_PORT:0}}
#  port: 8080

# parole di default (per tutti i profili, usate se il config server non e' accessibile)
asw.sentence: 
  wordservice: 
    words: default,default,default

# abilita il refresh, esponendo gli endpoint selezionati 
# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html 
management.endpoints.web.exposure.include: info,health,refresh 

--- 
spring: 
  profiles: subject
  application: 
    name: subject

server: 
  port: 8081
  
--- 
spring: 
  profiles: verb
  application: 
    name: verb

server: 
  port: 8082

--- 
spring: 
  profiles: object
  application: 
    name: object

server: 
  port: 8083
